project_id = "nulosjrmsqogskornbqh"

[functions.auth-login]
verify_jwt = false

[functions.create-athlete-login]
verify_jwt = false

[functions.list-credentials]
verify_jwt = false

[functions.reset-password]
verify_jwt = false